### ISSUE TITLE
 Undefined class constant 'JSonEncodeOptions'

### ISSUE THREAD

**Issue by ArminVieweg** [dogancelik/slim-json#4]
You have capitalize typo in your code, which throws this fatal error.

https://github.com/dogancelik/slim-json/blob/master/SlimJson/View.php#L35

`Config::JSonEncodeOptions`

The S must be small.

**Comment by dogancelik** [comment]
I'm sorry, I totally missed that!!!! Fixing it!

**Comment by ArminVieweg** [comment]
Thanks
