### ISSUE TITLE
UnitTest support

### ISSUE THREAD

**Issue by jeroendelau** [dogancelik/slim-json#6]
Love the lib, saves me a lot of time!

Two issues, 
1. 404 does not work as advertised.
2. I'm using there4/slim-test-helpers, and this lib is creating some unexpected responses. I narrowed it down to The use of Slim::getInstance(). By passing the $app in the constructor this can be circumvented. 
I've fixes in a fork.

**Comment by dogancelik** [comment]
Thanks for your feedback, I appreciate it!
I guess 404 issue is still there because I haven't merged #1, I'll take a look into that again.
Please send a pull request when you finish your changes.
