### ISSUE TITLE
Class 'Slim\Middleware' not found

### ISSUE THREAD

**Issue by igorjacauna** [dogancelik/slim-json#9]
Installed via composer.

When run the app shows the error.

Fatal error: Class 'Slim\Middleware' not found in C:\wamp\www\vendor\dogancelik\slim-json\SlimJson\Middleware.php on line 18

Using Slim 3.0

**Comment by dogancelik** [comment]
Currently Slim 2 is supported and as far as I know Slim 3 is different than 2 so we might need to rewrite. Patches are welcome :smiley:
